"use strict";
exports.__esModule = true;
exports.OPEN_ORDER_EVENTS = {
    OPEN_CANCEL_ORDER_EVENT: "OPEN_CANCEL_ORDER_EVENT",
    OPEN_BUY_ORDER_EVENT: "OPEN_BUY_ORDER_EVENT",
    OPEN_SELL_ORDER_EVENT: "OPEN_SELL_ORDER_EVENT"
};
